apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$ITEM # 通过一个变量 $ITEM 表示
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item $ITEM && sleep 5"]
      restartPolicy: Never